/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_handler_JHandler */

#ifndef _Included_com_wind_ndk_handler_JHandler
#define _Included_com_wind_ndk_handler_JHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_handler_JHandler
 * Method:    native_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wind_ndk_handler_JHandler_native_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ndk_handler_JHandler
 * Method:    native_send_message
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wind_ndk_handler_JHandler_native_1send_1message
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
